/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jFOperacao.java
 *
 * Created on 10/08/2014, 20:37:46
 */

package personalfinance;

import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.border.TitledBorder;
import personalfinance.classes.CentroCusto;
import personalfinance.classes.ClassConecta;
import personalfinance.classes.ComboItem;
import personalfinance.classes.Contas;
import personalfinance.classes.Funcoes;
import personalfinance.classes.Pessoas;

/**
 *
 * @author Luciano Carrafa Benfica
 */
public class jFOperacao extends javax.swing.JDialog {

    /** Creates new form jFOperacao */
    public jFOperacao() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelBackgroundjPanel = new javax.swing.JPanel();
        origemjPanel = new javax.swing.JPanel();
        contaOrigemjComboBox = new javax.swing.JComboBox();
        atualizaOrigemjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        painelDestinojPanel = new javax.swing.JPanel();
        contaDestinojLabel = new javax.swing.JLabel();
        contaDestinojComboBox = new javax.swing.JComboBox();
        atualizaContaDestinojButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        responsaveljComboBox = new javax.swing.JComboBox();
        atualizaResponsaveljButton = new javax.swing.JButton();
        numeroDocumentojLabel = new javax.swing.JLabel();
        numeroDocumentojTextField = new javax.swing.JTextField();
        tipoDocumentoOrigemjComboBox = new javax.swing.JComboBox();
        tipoDocumentoOrigemjLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        historicojTextField = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        dataLancamentojFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        valorFinaljFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        sairjButton = new javax.swing.JButton();
        executarjButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        centroCustojComboBox = new javax.swing.JComboBox();
        atualizaCentroCustojButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setName("Form"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(personalfinance.PersonalFinanceApp.class).getContext().getResourceMap(jFOperacao.class);
        painelBackgroundjPanel.setBackground(resourceMap.getColor("painelBackgroundjPanel.background")); // NOI18N
        painelBackgroundjPanel.setName("painelBackgroundjPanel"); // NOI18N

        origemjPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("origemjPanel.border.title"), 0, 0, null, resourceMap.getColor("origemjPanel.border.titleColor"))); // NOI18N
        origemjPanel.setName("origemjPanel"); // NOI18N

        contaOrigemjComboBox.setName("contaOrigemjComboBox"); // NOI18N

        atualizaOrigemjButton.setText(resourceMap.getString("atualizaOrigemjButton.text")); // NOI18N
        atualizaOrigemjButton.setContentAreaFilled(false);
        atualizaOrigemjButton.setName("atualizaOrigemjButton"); // NOI18N
        atualizaOrigemjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizaOrigemjButtonActionPerformed(evt);
            }
        });

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout origemjPanelLayout = new javax.swing.GroupLayout(origemjPanel);
        origemjPanel.setLayout(origemjPanelLayout);
        origemjPanelLayout.setHorizontalGroup(
            origemjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(origemjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(origemjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(origemjPanelLayout.createSequentialGroup()
                        .addComponent(contaOrigemjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(atualizaOrigemjButton)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        origemjPanelLayout.setVerticalGroup(
            origemjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(origemjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(origemjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contaOrigemjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atualizaOrigemjButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelDestinojPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("painelDestinojPanel.border.title"), 0, 0, null, resourceMap.getColor("painelDestinojPanel.border.titleColor"))); // NOI18N
        painelDestinojPanel.setName("painelDestinojPanel"); // NOI18N

        contaDestinojLabel.setText(resourceMap.getString("contaDestinojLabel.text")); // NOI18N
        contaDestinojLabel.setName("contaDestinojLabel"); // NOI18N

        contaDestinojComboBox.setName("contaDestinojComboBox"); // NOI18N

        atualizaContaDestinojButton.setText(resourceMap.getString("atualizaContaDestinojButton.text")); // NOI18N
        atualizaContaDestinojButton.setContentAreaFilled(false);
        atualizaContaDestinojButton.setFocusable(false);
        atualizaContaDestinojButton.setName("atualizaContaDestinojButton"); // NOI18N
        atualizaContaDestinojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizaContaDestinojButtonActionPerformed(evt);
            }
        });

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        responsaveljComboBox.setName("responsaveljComboBox"); // NOI18N

        atualizaResponsaveljButton.setText(resourceMap.getString("atualizaResponsaveljButton.text")); // NOI18N
        atualizaResponsaveljButton.setContentAreaFilled(false);
        atualizaResponsaveljButton.setFocusable(false);
        atualizaResponsaveljButton.setName("atualizaResponsaveljButton"); // NOI18N
        atualizaResponsaveljButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizaResponsaveljButtonActionPerformed(evt);
            }
        });

        numeroDocumentojLabel.setText(resourceMap.getString("numeroDocumentojLabel.text")); // NOI18N
        numeroDocumentojLabel.setName("numeroDocumentojLabel"); // NOI18N

        numeroDocumentojTextField.setText(resourceMap.getString("numeroDocumentojTextField.text")); // NOI18N
        numeroDocumentojTextField.setName("numeroDocumentojTextField"); // NOI18N

        tipoDocumentoOrigemjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Boleto", "Nota Fiscal", "Recibo", "Fatura", "Prolabore" }));
        tipoDocumentoOrigemjComboBox.setName("tipoDocumentoOrigemjComboBox"); // NOI18N

        tipoDocumentoOrigemjLabel.setText(resourceMap.getString("tipoDocumentoOrigemjLabel.text")); // NOI18N
        tipoDocumentoOrigemjLabel.setName("tipoDocumentoOrigemjLabel"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        historicojTextField.setText(resourceMap.getString("historicojTextField.text")); // NOI18N
        historicojTextField.setName("historicojTextField"); // NOI18N

        javax.swing.GroupLayout painelDestinojPanelLayout = new javax.swing.GroupLayout(painelDestinojPanel);
        painelDestinojPanel.setLayout(painelDestinojPanelLayout);
        painelDestinojPanelLayout.setHorizontalGroup(
            painelDestinojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDestinojPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDestinojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDestinojPanelLayout.createSequentialGroup()
                        .addGroup(painelDestinojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contaDestinojLabel)
                            .addComponent(jLabel3)
                            .addComponent(numeroDocumentojLabel)
                            .addGroup(painelDestinojPanelLayout.createSequentialGroup()
                                .addGroup(painelDestinojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tipoDocumentoOrigemjLabel)
                                    .addGroup(painelDestinojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(numeroDocumentojTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(responsaveljComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(contaDestinojComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 257, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelDestinojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(atualizaResponsaveljButton, 0, 0, Short.MAX_VALUE)
                                    .addComponent(atualizaContaDestinojButton, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(painelDestinojPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(273, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDestinojPanelLayout.createSequentialGroup()
                        .addGroup(painelDestinojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(historicojTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addComponent(tipoDocumentoOrigemjComboBox, 0, 253, Short.MAX_VALUE))
                        .addGap(61, 61, 61))))
        );
        painelDestinojPanelLayout.setVerticalGroup(
            painelDestinojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDestinojPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contaDestinojLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDestinojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contaDestinojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atualizaContaDestinojButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDestinojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(responsaveljComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atualizaResponsaveljButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numeroDocumentojLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numeroDocumentojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tipoDocumentoOrigemjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoDocumentoOrigemjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(historicojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setName("jPanel5"); // NOI18N

        dataLancamentojFormattedTextField.setFormatterFactory(Funcoes.setFormatoData());
        dataLancamentojFormattedTextField.setText(resourceMap.getString("dataLancamentojFormattedTextField.text")); // NOI18N
        dataLancamentojFormattedTextField.setName("dataLancamentojFormattedTextField"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        valorFinaljFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        valorFinaljFormattedTextField.setText(resourceMap.getString("valorFinaljFormattedTextField.text")); // NOI18N
        valorFinaljFormattedTextField.setName("valorFinaljFormattedTextField"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(valorFinaljFormattedTextField, javax.swing.GroupLayout.Alignment.TRAILING, 0, 0, Short.MAX_VALUE)
                    .addComponent(dataLancamentojFormattedTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataLancamentojFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorFinaljFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setName("jPanel6"); // NOI18N

        sairjButton.setIcon(resourceMap.getIcon("sairjButton.icon")); // NOI18N
        sairjButton.setText(resourceMap.getString("sairjButton.text")); // NOI18N
        sairjButton.setName("sairjButton"); // NOI18N
        sairjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairjButtonActionPerformed(evt);
            }
        });

        executarjButton.setIcon(resourceMap.getIcon("executarjButton.icon")); // NOI18N
        executarjButton.setText(resourceMap.getString("executarjButton.text")); // NOI18N
        executarjButton.setName("executarjButton"); // NOI18N
        executarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executarjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addComponent(executarjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sairjButton)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sairjButton)
                    .addComponent(executarjButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel1.border.title"), 0, 0, null, resourceMap.getColor("jPanel1.border.titleColor"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        centroCustojComboBox.setName("centroCustojComboBox"); // NOI18N

        atualizaCentroCustojButton.setText(resourceMap.getString("atualizaCentroCustojButton.text")); // NOI18N
        atualizaCentroCustojButton.setContentAreaFilled(false);
        atualizaCentroCustojButton.setName("atualizaCentroCustojButton"); // NOI18N
        atualizaCentroCustojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizaCentroCustojButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(centroCustojComboBox, 0, 263, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(atualizaCentroCustojButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(centroCustojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atualizaCentroCustojButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelBackgroundjPanelLayout = new javax.swing.GroupLayout(painelBackgroundjPanel);
        painelBackgroundjPanel.setLayout(painelBackgroundjPanelLayout);
        painelBackgroundjPanelLayout.setHorizontalGroup(
            painelBackgroundjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBackgroundjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelBackgroundjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(origemjPanel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelDestinojPanel, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelBackgroundjPanelLayout.setVerticalGroup(
            painelBackgroundjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBackgroundjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(origemjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelDestinojPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelBackgroundjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelBackgroundjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    ClassConecta conecta = new ClassConecta();

    /**
     *
     */
    int operacao; // OPERAÇÃO QUE DEFINIRÁ SE É DEPÓSITO, TRANSFERENCIA OU SAQUE
    /**
     *
     */
    String tipoRepasse = null;
    /**
     *
     */
    int valorCheque;
    /**
     *
     */
    public String operacaoDesc  = null;


    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        atualizaContaDestinojButton.setVisible(false);

        ClassConecta.conecta();

        //Saque
        setLocationRelativeTo(null);
        if (operacao == 1){
            TitledBorder tituloPainel = new TitledBorder("Saque");
            Font fontPainel = new Font("Tahoma", 0, 11);
            Color corTituloPainel = new Color(0, 0, 153);
            painelDestinojPanel.setBorder(tituloPainel);
            tituloPainel.setTitleFont(fontPainel);
            tituloPainel.setTitleColor(corTituloPainel);
            contaDestinojLabel.setText("Conta");
        }

        //Se a operação for Depósito ou Transferência irá ocultar os campos
        if ((operacao == 0) || (operacao == 2) ){
            numeroDocumentojTextField.setVisible(false);
            tipoDocumentoOrigemjComboBox.setVisible(false);
            numeroDocumentojLabel.setVisible(false);
            tipoDocumentoOrigemjComboBox.setVisible(false);
            tipoDocumentoOrigemjLabel.setVisible(false);
        }

        if (operacao != 2) {
                //Transferencia
                origemjPanel.setVisible(false);

            } else {
                origemjPanel.setVisible(true);
        }
        try {
            dataLancamentojFormattedTextField.setText(Funcoes.getNowBR());
        } catch (ParseException ex) {
            Logger.getLogger(jFOperacao.class.getName()).log(Level.SEVERE, null, ex);
        }
        atualizaContaDestinojButtonActionPerformed(null);
        atualizaResponsaveljButtonActionPerformed(null);
        atualizaCentroCustojButtonActionPerformed(null);
        atualizaOrigemjButtonActionPerformed(null);
//        atualizarContaDestjButtonActionPerformed(null);
//        atualizaPessoajButtonActionPerformed(null);

    }//GEN-LAST:event_formWindowOpened

    private void sairjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairjButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_sairjButtonActionPerformed

    private void atualizaOrigemjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizaOrigemjButtonActionPerformed
        // TODO add your handling code here:
        try {
            Contas oConta = new Contas();
            ResultSet rs = null;
            rs = oConta.getConsultar();
            contaOrigemjComboBox.removeAllItems();
            while (rs.next()) {
                contaOrigemjComboBox.addItem(new ComboItem(rs.getInt("COD_CONTAS"), rs.getString("BANCO")));
            }
            contaOrigemjComboBox.updateUI();
        } catch (SQLException ex) {
            Logger.getLogger(jFLivroCaixa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_atualizaOrigemjButtonActionPerformed

    private void atualizaContaDestinojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizaContaDestinojButtonActionPerformed
        // TODO add your handling code here:
        try {
            Contas oConta = new Contas();
            ResultSet rs = null;
            rs = oConta.getConsultar();
            contaDestinojComboBox.removeAllItems();
            while (rs.next()) {
                contaDestinojComboBox.addItem(new ComboItem(rs.getInt("COD_CONTAS"), rs.getString("BANCO")));
            }
            contaDestinojComboBox.updateUI();
        } catch (SQLException ex) {
            Logger.getLogger(jFLivroCaixa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_atualizaContaDestinojButtonActionPerformed

    private void atualizaResponsaveljButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizaResponsaveljButtonActionPerformed
        // TODO add your handling code here:
        try {
            Pessoas oPessoa = new Pessoas();
            ResultSet rs = null;
            rs = oPessoa.getConsultar();
            responsaveljComboBox.removeAllItems();
            while (rs.next()) {
                responsaveljComboBox.addItem(new ComboItem(rs.getInt(1), rs.getString(2)));
            }
            responsaveljComboBox.updateUI();
        } catch (SQLException ex) {
            Logger.getLogger(jFContas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_atualizaResponsaveljButtonActionPerformed

    private void executarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executarjButtonActionPerformed
         //TODO add your handling code here:
        try {
            //Verificar campos obrigatorios
            if ((contaOrigemjComboBox.getSelectedIndex() == contaDestinojComboBox.getSelectedIndex()) && (operacao == 2)) {
                JOptionPane.showMessageDialog(null, "A conta de origem não pode ser igual a de destino.", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                contaOrigemjComboBox.grabFocus();
                return;
            }
            if (valorFinaljFormattedTextField.getText().length() == 0) {
                JOptionPane.showMessageDialog(null, "O Campo <Valor do Lançamento:> é obrigatório.", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                valorFinaljFormattedTextField.grabFocus();
                return;
            }
            if ((contaDestinojComboBox.getSelectedIndex() == -1) && (operacao == 2)) {
                JOptionPane.showMessageDialog(null, "O Campo <Conta Destino> é obrigatório.", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                contaDestinojComboBox.grabFocus();
                return;
            }
            if (responsaveljComboBox.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(null, "O Campo <Responsável> é obrigatório.", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                responsaveljComboBox.grabFocus();
                return;
            }
            this.setAlwaysOnTop(false);
            ComboItem codConta = (ComboItem) contaDestinojComboBox.getSelectedItem();
            ComboItem codContaOrigem = (ComboItem) contaOrigemjComboBox.getSelectedItem();
            ComboItem codPessoa = (ComboItem) responsaveljComboBox.getSelectedItem();
            ComboItem codCentroCusto = (ComboItem) centroCustojComboBox.getSelectedItem();

            switch (operacao) {
                case 0:
                    //Deposito
                    Integer numDoc = 0;
                    operacaoDesc = "Deposito";
                    Funcoes.setLancContabil(conecta, dataLancamentojFormattedTextField.getText(), codCentroCusto.getId(), codConta.getId(), numDoc, codPessoa.getId(), operacaoDesc, historicojTextField.getText(), Double.parseDouble(valorFinaljFormattedTextField.getValue().toString()), (String) tipoDocumentoOrigemjComboBox.getSelectedItem());
                    break;

                    case 1:
                    //Saque
                    operacaoDesc = "Saque";
                    //setLancContabil(codConta.getId(), codCliente.getId(), historicojTextField.getText(), Double.parseDouble(valorTotalFinaljFormattedTextField.getValue().toString()) * -1);
                    Funcoes.setLancContabil(conecta, dataLancamentojFormattedTextField.getText(), codCentroCusto.getId(), codConta.getId(), Integer.parseInt(numeroDocumentojTextField.getText()), codPessoa.getId(), operacaoDesc, historicojTextField.getText(), Double.parseDouble(valorFinaljFormattedTextField.getValue().toString()) * -1, "Saque"  );
                    break;
                    case 2:
                    //Transferencia
                    operacaoDesc = "Transferencia";
                    String dePara = "de: " + codContaOrigem.toString() + " para: " + codConta.toString();
                    Funcoes.setLancContabil(conecta, dataLancamentojFormattedTextField.getText(), codCentroCusto.getId(), codContaOrigem.getId(), 1, codPessoa.getId(), "Saque", historicojTextField.getText()+ dePara , Double.parseDouble(valorFinaljFormattedTextField.getValue().toString()) * -1, "saque para tranferencia"  );
                    Funcoes.setLancContabil(conecta, dataLancamentojFormattedTextField.getText(), codCentroCusto.getId(), codConta.getId(), 0, codPessoa.getId(), "Depósito", historicojTextField.getText()+ dePara , Double.parseDouble(valorFinaljFormattedTextField.getValue().toString()),"deposito para transferencia"   );
                    break;



            }
            ClassConecta.con.commit();

            JOptionPane.showMessageDialog(null, operacaoDesc + " realizado(a) com sucesso!", "SUCESSO!", JOptionPane.INFORMATION_MESSAGE);
            sairjButtonActionPerformed(null);


        } catch (SQLException ex) {
            Logger.getLogger(jFOperacao.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(jFOperacao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_executarjButtonActionPerformed

    private void atualizaCentroCustojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizaCentroCustojButtonActionPerformed
        // TODO add your handling code here:

        try {
            CentroCusto oCentroCusto = new CentroCusto();
            ResultSet rs = null;
            rs = oCentroCusto.getConsultar();
            contaOrigemjComboBox.removeAllItems();
            while (rs.next()) {
                centroCustojComboBox.addItem(new ComboItem(rs.getInt("COD_CENTRO_CUSTO"), rs.getString("NOME_CENTRO_CUSTO")));
            }
            contaOrigemjComboBox.updateUI();
        } catch (SQLException ex) {
            Logger.getLogger(jFOperacao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_atualizaCentroCustojButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFOperacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizaCentroCustojButton;
    private javax.swing.JButton atualizaContaDestinojButton;
    private javax.swing.JButton atualizaOrigemjButton;
    private javax.swing.JButton atualizaResponsaveljButton;
    private javax.swing.JComboBox centroCustojComboBox;
    private javax.swing.JComboBox contaDestinojComboBox;
    private javax.swing.JLabel contaDestinojLabel;
    private javax.swing.JComboBox contaOrigemjComboBox;
    private javax.swing.JFormattedTextField dataLancamentojFormattedTextField;
    private javax.swing.JButton executarjButton;
    private javax.swing.JTextField historicojTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel numeroDocumentojLabel;
    private javax.swing.JTextField numeroDocumentojTextField;
    private javax.swing.JPanel origemjPanel;
    private javax.swing.JPanel painelBackgroundjPanel;
    private javax.swing.JPanel painelDestinojPanel;
    private javax.swing.JComboBox responsaveljComboBox;
    private javax.swing.JButton sairjButton;
    private javax.swing.JComboBox tipoDocumentoOrigemjComboBox;
    private javax.swing.JLabel tipoDocumentoOrigemjLabel;
    private javax.swing.JFormattedTextField valorFinaljFormattedTextField;
    // End of variables declaration//GEN-END:variables

}
