/*
 * PersonalFinanceView.java
 */

package personalfinance;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.TaskMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import personalfinance.classes.ClassConecta;
import personalfinance.classes.Historicos;
import personalfinance.classes.Usuarios;

/**
 * The application's main frame.
 */
public class PersonalFinanceView extends FrameView {

    public PersonalFinanceView(SingleFrameApplication app) {
        super(app);

        initComponents();

        String usuario2 = PersonalFinanceApp.usuario;

        menuBar.setVisible(false);
        menujTabbedPane.setVisible(false);


        // status bar initialization - message timeout, idle icon and busy animation, etc
        ResourceMap resourceMap = getResourceMap();
        int messageTimeout = resourceMap.getInteger("StatusBar.messageTimeout");
        messageTimer = new Timer(messageTimeout, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                statusMessageLabel.setText("");
            }
        });
        messageTimer.setRepeats(false);
        int busyAnimationRate = resourceMap.getInteger("StatusBar.busyAnimationRate");
        for (int i = 0; i < busyIcons.length; i++) {
            busyIcons[i] = resourceMap.getIcon("StatusBar.busyIcons[" + i + "]");
        }
        busyIconTimer = new Timer(busyAnimationRate, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                busyIconIndex = (busyIconIndex + 1) % busyIcons.length;
                statusAnimationLabel.setIcon(busyIcons[busyIconIndex]);
            }
        });
        idleIcon = resourceMap.getIcon("StatusBar.idleIcon");
        statusAnimationLabel.setIcon(idleIcon);
        progressBar.setVisible(false);

        // connecting action tasks to status bar via TaskMonitor
        TaskMonitor taskMonitor = new TaskMonitor(getApplication().getContext());
        taskMonitor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                String propertyName = evt.getPropertyName();
                if ("started".equals(propertyName)) {
                    if (!busyIconTimer.isRunning()) {
                        statusAnimationLabel.setIcon(busyIcons[0]);
                        busyIconIndex = 0;
                        busyIconTimer.start();
                    }
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(true);
                } else if ("done".equals(propertyName)) {
                    busyIconTimer.stop();
                    statusAnimationLabel.setIcon(idleIcon);
                    progressBar.setVisible(false);
                    progressBar.setValue(0);
                } else if ("message".equals(propertyName)) {
                    String text = (String)(evt.getNewValue());
                    statusMessageLabel.setText((text == null) ? "" : text);
                    messageTimer.restart();
                } else if ("progress".equals(propertyName)) {
                    int value = (Integer)(evt.getNewValue());
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(false);
                    progressBar.setValue(value);
                }
            }
        });
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = PersonalFinanceApp.getApplication().getMainFrame();
            aboutBox = new PersonalFinanceAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        PersonalFinanceApp.getApplication().show(aboutBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        usuario2jLabel = new javax.swing.JLabel();
        fundojPanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        menujTabbedPane = new javax.swing.JTabbedPane();
        cadastrojPanel = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        pessoasjButton = new javax.swing.JButton();
        contasjButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        historicojButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        sairSistemajButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jButton1 = new javax.swing.JButton();
        livroCaixajButton = new javax.swing.JButton();
        panelValidarjPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        validaUsuariojTextField = new javax.swing.JTextField();
        atualizajButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        cadastrosjMenu = new javax.swing.JMenu();
        pessoasjMenuItem = new javax.swing.JMenuItem();
        contasjMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();
        statusPanel = new javax.swing.JPanel();
        javax.swing.JSeparator statusPanelSeparator = new javax.swing.JSeparator();
        statusMessageLabel = new javax.swing.JLabel();
        statusAnimationLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();

        mainPanel.setName("mainPanel"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(personalfinance.PersonalFinanceApp.class).getContext().getResourceMap(PersonalFinanceView.class);
        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setName("jPanel3"); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(1));
        jPanel4.setName("jPanel4"); // NOI18N

        usuario2jLabel.setText(resourceMap.getString("usuario2jLabel.text")); // NOI18N
        usuario2jLabel.setName("usuario2jLabel"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usuario2jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usuario2jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(365, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        fundojPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fundojPanel.setName("fundojPanel"); // NOI18N

        jPanel6.setBackground(resourceMap.getColor("jPanel6.background")); // NOI18N
        jPanel6.setName("jPanel6"); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 763, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        menujTabbedPane.setName("menujTabbedPane"); // NOI18N

        cadastrojPanel.setBackground(resourceMap.getColor("cadastrojPanel.background")); // NOI18N
        cadastrojPanel.setName("cadastrojPanel"); // NOI18N

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setName("jToolBar1"); // NOI18N

        jSeparator1.setBackground(resourceMap.getColor("jSeparator1.background")); // NOI18N
        jSeparator1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jSeparator1.setForeground(resourceMap.getColor("jSeparator1.foreground")); // NOI18N
        jSeparator1.setName("jSeparator1"); // NOI18N
        jToolBar1.add(jSeparator1);

        pessoasjButton.setIcon(resourceMap.getIcon("pessoasjButton.icon")); // NOI18N
        pessoasjButton.setText(resourceMap.getString("pessoasjButton.text")); // NOI18N
        pessoasjButton.setFocusable(false);
        pessoasjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pessoasjButton.setName("pessoasjButton"); // NOI18N
        pessoasjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pessoasjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pessoasjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(pessoasjButton);

        contasjButton.setIcon(resourceMap.getIcon("contasjButton.icon")); // NOI18N
        contasjButton.setText(resourceMap.getString("contasjButton.text")); // NOI18N
        contasjButton.setFocusable(false);
        contasjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        contasjButton.setName("contasjButton"); // NOI18N
        contasjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        contasjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contasjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(contasjButton);

        jSeparator2.setName("jSeparator2"); // NOI18N
        jToolBar1.add(jSeparator2);

        historicojButton.setIcon(resourceMap.getIcon("historicojButton.icon")); // NOI18N
        historicojButton.setText(resourceMap.getString("historicojButton.text")); // NOI18N
        historicojButton.setFocusable(false);
        historicojButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        historicojButton.setName("historicojButton"); // NOI18N
        historicojButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        historicojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historicojButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(historicojButton);

        jSeparator3.setName("jSeparator3"); // NOI18N
        jToolBar1.add(jSeparator3);

        sairSistemajButton.setIcon(resourceMap.getIcon("sairSistemajButton.icon")); // NOI18N
        sairSistemajButton.setText(resourceMap.getString("sairSistemajButton.text")); // NOI18N
        sairSistemajButton.setFocusable(false);
        sairSistemajButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sairSistemajButton.setName("sairSistemajButton"); // NOI18N
        sairSistemajButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        sairSistemajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairSistemajButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(sairSistemajButton);

        javax.swing.GroupLayout cadastrojPanelLayout = new javax.swing.GroupLayout(cadastrojPanel);
        cadastrojPanel.setLayout(cadastrojPanelLayout);
        cadastrojPanelLayout.setHorizontalGroup(
            cadastrojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
        );
        cadastrojPanelLayout.setVerticalGroup(
            cadastrojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastrojPanelLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menujTabbedPane.addTab(resourceMap.getString("cadastrojPanel.TabConstraints.tabTitle"), cadastrojPanel); // NOI18N

        jPanel5.setBackground(resourceMap.getColor("jPanel5.background")); // NOI18N
        jPanel5.setName("jPanel5"); // NOI18N

        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);
        jToolBar2.setName("jToolBar2"); // NOI18N

        jSeparator4.setName("jSeparator4"); // NOI18N
        jToolBar2.add(jSeparator4);

        jButton1.setIcon(resourceMap.getIcon("jButton1.icon")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setName("jButton1"); // NOI18N
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton1);

        livroCaixajButton.setIcon(resourceMap.getIcon("livroCaixajButton.icon")); // NOI18N
        livroCaixajButton.setText(resourceMap.getString("livroCaixajButton.text")); // NOI18N
        livroCaixajButton.setFocusable(false);
        livroCaixajButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        livroCaixajButton.setName("livroCaixajButton"); // NOI18N
        livroCaixajButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        livroCaixajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                livroCaixajButtonActionPerformed(evt);
            }
        });
        jToolBar2.add(livroCaixajButton);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
        );

        menujTabbedPane.addTab(resourceMap.getString("jPanel5.TabConstraints.tabTitle"), jPanel5); // NOI18N

        javax.swing.GroupLayout fundojPanelLayout = new javax.swing.GroupLayout(fundojPanel);
        fundojPanel.setLayout(fundojPanelLayout);
        fundojPanelLayout.setHorizontalGroup(
            fundojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(fundojPanelLayout.createSequentialGroup()
                .addComponent(menujTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        fundojPanelLayout.setVerticalGroup(
            fundojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundojPanelLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menujTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelValidarjPanel.setBackground(resourceMap.getColor("panelValidarjPanel.background")); // NOI18N
        panelValidarjPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelValidarjPanel.setName("panelValidarjPanel"); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel2.border.title"), 0, 0, null, resourceMap.getColor("jPanel2.border.titleColor"))); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N

        validaUsuariojTextField.setText(resourceMap.getString("validaUsuariojTextField.text")); // NOI18N
        validaUsuariojTextField.setName("validaUsuariojTextField"); // NOI18N

        atualizajButton.setIcon(resourceMap.getIcon("atualizajButton.icon")); // NOI18N
        atualizajButton.setText(resourceMap.getString("atualizajButton.text")); // NOI18N
        atualizajButton.setName("atualizajButton"); // NOI18N
        atualizajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizajButtonActionPerformed(evt);
            }
        });

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(validaUsuariojTextField)
                    .addComponent(atualizajButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(validaUsuariojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizajButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelValidarjPanelLayout = new javax.swing.GroupLayout(panelValidarjPanel);
        panelValidarjPanel.setLayout(panelValidarjPanelLayout);
        panelValidarjPanelLayout.setHorizontalGroup(
            panelValidarjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelValidarjPanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelValidarjPanelLayout.setVerticalGroup(
            panelValidarjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelValidarjPanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(fundojPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelValidarjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(fundojPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelValidarjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 241, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menuBar.setName("menuBar"); // NOI18N

        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        cadastrosjMenu.setText(resourceMap.getString("cadastrosjMenu.text")); // NOI18N

        pessoasjMenuItem.setText(resourceMap.getString("pessoasjMenuItem.text")); // NOI18N
        pessoasjMenuItem.setName("pessoasjMenuItem"); // NOI18N
        pessoasjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pessoasjMenuItemActionPerformed(evt);
            }
        });
        cadastrosjMenu.add(pessoasjMenuItem);

        contasjMenuItem.setText(resourceMap.getString("contasjMenuItem.text")); // NOI18N
        contasjMenuItem.setName("contasjMenuItem"); // NOI18N
        cadastrosjMenu.add(contasjMenuItem);

        fileMenu.add(cadastrosjMenu);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(personalfinance.PersonalFinanceApp.class).getContext().getActionMap(PersonalFinanceView.class, this);
        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setText(resourceMap.getString("exitMenuItem.text")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setText(resourceMap.getString("aboutMenuItem.text")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        statusPanel.setName("statusPanel"); // NOI18N

        statusPanelSeparator.setName("statusPanelSeparator"); // NOI18N

        statusMessageLabel.setName("statusMessageLabel"); // NOI18N

        statusAnimationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusAnimationLabel.setName("statusAnimationLabel"); // NOI18N

        progressBar.setName("progressBar"); // NOI18N

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusPanelSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusMessageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 597, Short.MAX_VALUE)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusAnimationLabel)
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addComponent(statusPanelSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusMessageLabel)
                    .addComponent(statusAnimationLabel)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        setComponent(mainPanel);
        setMenuBar(menuBar);
        setStatusBar(statusPanel);
    }// </editor-fold>//GEN-END:initComponents

   ClassConecta conecta = new ClassConecta();

   public Integer cod_pessoa;
   public String usuario_logado;




    private void pessoasjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pessoasjMenuItemActionPerformed
        // TODO add your handling code here:

        jFPessoas oFormPessoas = new jFPessoas();

        oFormPessoas.conecta = conecta;
        System.out.println(cod_pessoa);
        oFormPessoas.cod_acesso_usuario = cod_pessoa;
        oFormPessoas.pessoas_usuario_logado = usuario_logado;
        oFormPessoas.setTitle("Cadastro Pessoas");
        oFormPessoas.pack();
        oFormPessoas.setLocationRelativeTo(null);
        oFormPessoas.setVisible(true);
    }//GEN-LAST:event_pessoasjMenuItemActionPerformed

    private void atualizajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizajButtonActionPerformed
        // TODO add your handling code here:
        Usuarios oUsuario = new Usuarios();

        cod_pessoa = Integer.parseInt(validaUsuariojTextField.getText());
//        usuario_logado;

         String usuario = PersonalFinanceApp.usuario;

        try {

                oUsuario.setCod_pessoa(cod_pessoa);
                ResultSet rs = null;
                rs = oUsuario.getConsultar();

                if (rs.next()){
                    
                    usuario_logado = rs.getString("PESSOA");
                    usuario2jLabel.setText("Usuário logado: " + usuario_logado);
                

                panelValidarjPanel.setVisible(false);
                menuBar.setVisible(true);
                menujTabbedPane.setVisible(true);

// *******************INCLUINDO DADOS NO HISTORICO*******************************************************

                String data = "dd/MM/yyyy";
                String hora = "h:mm - a";
                String data1, hora1;

                java.util.Date agora = new java.util.Date();
                SimpleDateFormat formata = new SimpleDateFormat(data);
                data1 = formata.format(agora);
                formata = new SimpleDateFormat(hora);
                hora1 = formata.format(agora);
                System.out.println(data1);

                System.out.print(data1+" "+ hora1);

                Historicos oHistorico = new Historicos();

                oHistorico.setCod_pessoa(cod_pessoa);
                oHistorico.setHistorico("USUÁRIO LOGOU NO SISTEMA AS: " + data1 + " " + hora1);
                oHistorico.setPessoa(usuario_logado);
                oHistorico.setData(data1 +" "+ hora1);
                oHistorico.setTipo_historico("ENTRADA NO SISTEMA");
                oHistorico.setCadastrar();

                ClassConecta.con.commit();
                ClassConecta.con.setAutoCommit(true);

// *******************FIM DAINCLUSÃO DE DADOS NO HISTORICO*************************************************

                
            }

        } catch (SQLException ex) {
            Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_atualizajButtonActionPerformed

    private void pessoasjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pessoasjButtonActionPerformed
        // TODO add your handling code here:
        jFPessoas oFormPessoas = new jFPessoas();

        oFormPessoas.conecta = conecta;
        System.out.println(cod_pessoa);
        oFormPessoas.cod_acesso_usuario = cod_pessoa;
        oFormPessoas.pessoas_usuario_logado = usuario_logado;
        oFormPessoas.setTitle("Cadastro Pessoas");
        oFormPessoas.pack();
        oFormPessoas.setLocationRelativeTo(null);
        oFormPessoas.setVisible(true);
    }//GEN-LAST:event_pessoasjButtonActionPerformed

    private void contasjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contasjButtonActionPerformed
        // TODO add your handling code here:
        jFContas oFormContas = new jFContas();

        oFormContas.conecta = conecta;
        oFormContas.cod_acesso_usuario = cod_pessoa;
        oFormContas.contas_usuario_logado = usuario_logado;
        oFormContas.setTitle("Cadastro Contas");
        oFormContas.pack();
        oFormContas.setLocationRelativeTo(null);
        oFormContas.setVisible(true);

    }//GEN-LAST:event_contasjButtonActionPerformed

    private void historicojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historicojButtonActionPerformed
        // TODO add your handling code here:
        jFHistoricos oFormHistorico = new jFHistoricos();

        oFormHistorico.setDefaultCloseOperation(jFHistoricos.DISPOSE_ON_CLOSE);
        oFormHistorico.setTitle("HISTÓRICO");
        oFormHistorico.pack();
        oFormHistorico.setLocationRelativeTo(null);
        oFormHistorico.setModal(true);
        oFormHistorico.setVisible(true);
    }//GEN-LAST:event_historicojButtonActionPerformed

    private void sairSistemajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairSistemajButtonActionPerformed
        try {
            // TODO add your handling code here:
            ClassConecta.con.close();
        } catch (SQLException ex) {
            Logger.getLogger(PersonalFinanceView.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_sairSistemajButtonActionPerformed

    private void livroCaixajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_livroCaixajButtonActionPerformed
        // TODO add your handling code here:
        jFLivroCaixa oFormLivroCaixa = new jFLivroCaixa();

        oFormLivroCaixa.conecta = conecta;
        oFormLivroCaixa.cod_usuario_logado = cod_pessoa;
        oFormLivroCaixa.nome_usuario_logado = usuario_logado;
        oFormLivroCaixa.setDefaultCloseOperation(jFHistoricos.DISPOSE_ON_CLOSE);
        oFormLivroCaixa.setTitle("Livro Caixa");
        oFormLivroCaixa.pack();
        oFormLivroCaixa.setLocationRelativeTo(null);
        oFormLivroCaixa.setModal(true);
        oFormLivroCaixa.setVisible(true);
    }//GEN-LAST:event_livroCaixajButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jFCentroCusto oFormCentrocusto = new jFCentroCusto();

        oFormCentrocusto.setDefaultCloseOperation(jFCentroCusto.DISPOSE_ON_CLOSE);
        oFormCentrocusto.setTitle("Centro de custo");
        oFormCentrocusto.pack();
        oFormCentrocusto.setLocationRelativeTo(null);
        oFormCentrocusto.setModal(true);
        oFormCentrocusto.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizajButton;
    private javax.swing.JPanel cadastrojPanel;
    private javax.swing.JMenu cadastrosjMenu;
    private javax.swing.JButton contasjButton;
    private javax.swing.JMenuItem contasjMenuItem;
    private javax.swing.JPanel fundojPanel;
    private javax.swing.JButton historicojButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JButton livroCaixajButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTabbedPane menujTabbedPane;
    private javax.swing.JPanel panelValidarjPanel;
    private javax.swing.JButton pessoasjButton;
    private javax.swing.JMenuItem pessoasjMenuItem;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JButton sairSistemajButton;
    private javax.swing.JLabel statusAnimationLabel;
    private javax.swing.JLabel statusMessageLabel;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JLabel usuario2jLabel;
    private javax.swing.JTextField validaUsuariojTextField;
    // End of variables declaration//GEN-END:variables

    private final Timer messageTimer;
    private final Timer busyIconTimer;
    private final Icon idleIcon;
    private final Icon[] busyIcons = new Icon[15];
    private int busyIconIndex = 0;

    private JDialog aboutBox;
}
